Repository mjg59/python-broadlink, pull requests merged in 2024-04, with the labels that each got.

#613 Add ability to RF scan a specific frequency
  broadlink/remote.py
  cli/broadlink_cli
Labels: breaking-change, feature

#762 Supports mp1s to obtain power information.
  broadlink/switch.py
Labels: bug

#783 Rename MP1S state parameters
  broadlink/__init__.py
  broadlink/switch.py
Labels: code-quality

#784 Add support for BG Electrical EHC31 (0x6480)
  broadlink/__init__.py
  broadlink/switch.py
Labels: feature

#790 Fix s3.get_subdevices()
  broadlink/hub.py
Labels: bug

#794 Fix type hints
  broadlink/__init__.py
  broadlink/cover.py
  broadlink/device.py
  broadlink/hub.py
  broadlink/light.py
  broadlink/remote.py
  broadlink/sensor.py
  broadlink/switch.py
Labels: bug

#797 Make type hints compatible with Python 3.6
  broadlink/__init__.py
  broadlink/device.py
  broadlink/helpers.py
  broadlink/hub.py
  broadlink/light.py
  broadlink/remote.py
  broadlink/switch.py
  cli/broadlink_cli
Labels: bug
